from fastembed_vectorstore import FastembedVectorstore, FastembedEmbeddingModel
import time

documents = [
    "The old clock on the wall ticked loudly in the silent room.",
    "She planted sunflowers in her garden every spring without fail.",
    "The mysterious package arrived at midnight on Tuesday.",
    "Children laughed and played in the newly fallen snow.",
    "The ancient book contained secrets lost to time.",
    "He practiced piano for hours every day to perfect his skills.",
    "The cat chased the red laser dot around the living room.",
    "Fresh coffee aroma filled the small café each morning.",
    "Waves crashed against the rocky shore at sunset.",
    "The painting in the museum captivated all who saw it.",
    "Stars twinkled brightly in the clear night sky.",
    "The chef prepared a magnificent feast for the celebration.",
    "Autumn leaves danced in the gentle October breeze.",
    "The train whistled as it passed through the sleeping town.",
    "She wrote poetry by candlelight every evening.",
    "The old guitar produced beautiful melodies in skilled hands.",
    "Rain tapped gently on the windowpane during the storm.",
    "The butterfly landed delicately on the purple flower.",
    "He told fascinating stories about his travels abroad.",
    "The library was filled with the scent of old books.",
    "The mountain peak disappeared into the swirling clouds above.",
    "Bees buzzed busily around the blooming lavender bushes.",
    "The antique mirror reflected memories of generations past.",
    "She discovered an old map hidden in the attic trunk.",
    "The street musician played haunting melodies on his violin.",
    "Morning dew sparkled like diamonds on the spider's web.",
    "The lighthouse beam guided ships safely through the fog.",
    "He carved intricate designs into the wooden tabletop.",
    "The bakery filled the neighborhood with the smell of fresh bread.",
    "A shooting star streaked across the midnight sky.",
    "The old bridge creaked as the wind howled through its beams.",
    "She collected seashells along the deserted beach at dawn.",
    "The grandfather clock chimed twelve times at midnight.",
    "The fireflies danced in the warm summer evening air.",
    "He built a treehouse high in the ancient oak tree.",
    "The vintage car purred to life after years of neglect.",
    "The snowflakes fell silently on the frozen lake surface.",
    "She painted landscapes that captured the soul of nature.",
    "The wind chimes sang sweetly in the afternoon breeze.",
    "The old well contained water as clear as crystal.",
    "The blacksmith's hammer rang out across the village square.",
    "The cat slept on the windowsill.",
    "She walked through the forest with a lantern.",
    "He writes code better at night.",
    "The stars twinkled in the clear sky.",
    "I had toast and eggs for breakfast.",
    "The car wouldn’t start this morning.",
    "We watched the sunrise from the hilltop.",
    "She lost her keys at the mall.",
    "The book was surprisingly interesting.",
    "They danced under the moonlight.",
    "Rain tapped gently on the roof.",
    "He forgot his umbrella at the café.",
    "The dog barked at the delivery man.",
    "She paints with watercolors on weekends.",
    "We found a shortcut through the park.",
    "He plays guitar in a local band.",
    "She hummed a soft tune while working.",
    "They went hiking in the mountains.",
    "The garden was full of blooming roses.",
    "He sipped his coffee and smiled.",
    "She wore her favorite red scarf.",
    "The train arrived five minutes late.",
    "I enjoy long walks on quiet roads.",
    "They moved to a new apartment last week.",
    "He solved the puzzle in record time.",
    "The bakery smells like fresh bread.",
    "She teaches math at a nearby school.",
    "The waves crashed loudly on the shore.",
    "He dropped his phone on the sidewalk.",
    "They adopted a puppy named Max.",
    "The library was quiet and peaceful.",
    "She baked cookies for the fundraiser.",
    "He likes to jog early in the morning.",
    "The wind rustled the dry leaves.",
    "They met at a coffee shop downtown.",
    "She writes poetry in her journal.",
    "The child built a sandcastle on the beach.",
    "He fixed the leaky faucet himself.",
    "They played board games all afternoon.",
    "She studied French during summer break.",
    "The restaurant was packed with people.",
    "He wore mismatched socks to work.",
    "She lit a candle and turned off the lights.",
    "The ice cream melted in the sun.",
    "They cheered as the fireworks exploded.",
    "He found a wallet on the street.",
    "She drank tea while reading a novel.",
    "They stayed up all night talking.",
    "The cat chased a laser dot on the wall.",
    "He built a birdhouse from scratch.",
    "She took a nap under the tree.",
    "The museum had a new dinosaur exhibit.",
    "They planted sunflowers in the backyard.",
    "He took a picture of the sunset.",
    "She wore headphones while studying.",
    "The bus stopped at every corner.",
    "He washed his car on Sunday.",
    "They watched a movie together.",
    "She grew tomatoes in her balcony garden.",
    "The snow covered everything overnight.",
    "He practiced the piano for two hours.",
    "She drew sketches in her notebook.",
    "They bought souvenirs from the trip.",
    "The fish swam in circles.",
    "He sharpened his pencils before class.",
    "She wore rain boots to school.",
    "They listened to the sound of rain.",
    "The suitcase was too heavy to lift.",
    "He packed lunch for the road trip.",
    "She tried a new recipe for dinner.",
    "They waved at the passing train.",
    "The light flickered in the hallway.",
    "He forgot his homework at home.",
    "She whispered a secret to her friend.",
    "They walked barefoot on the grass.",
    "The dog rolled in the mud.",
    "He played chess with his grandfather.",
    "She bought flowers for the table.",
    "They watched clouds float by.",
    "The treehouse was their secret hideout.",
    "He drank lemonade on the porch.",
    "She drew stars on the sidewalk with chalk.",
    "They climbed to the top of the hill.",
    "The kitten meowed for food.",
    "He wrote a letter to his pen pal.",
    "She made a paper airplane and flew it.",
    "They sang songs around the campfire.",
    "The frog jumped into the pond.",
    "He lost track of time while reading.",
    "She wore sunglasses indoors.",
    "They explored the old abandoned barn.",
    "The cookies were still warm.",
    "He found a shiny rock on the trail.",
    "She folded paper cranes for good luck.",
    "They raced their bikes down the street.",
    "The moon was full and bright.",
    "He made a snow angel in the yard.",
    "She hummed a lullaby to her baby.",
    "They drew maps of imaginary worlds.",
    "The owl hooted from the tree.",
    "He caught a firefly in a jar.",
    "She listened to classical music.",
    "They watched the storm roll in.",
    "The clock struck midnight.",
    "The robot jumps over an idea gracefully.",
    "A scientist admires a book happily.",
    "An artist runs to the wall loudly.",
    "My friend admires the computer boldly.",
    "A scientist builds a book gracefully.",
    "The teacher looks at an idea sadly.",
    "The cat admires the star quickly.",
    "The cat jumps over a poem quickly.",
    "An artist runs to a poem silently.",
    "An artist admires the mountain silently.",
    "A dog builds the mountain loudly.",
    "The teacher runs to the computer happily.",
    "The robot jumps over an idea boldly.",
    "The robot admires the wall happily.",
    "The robot destroys the computer boldly.",
    "My friend destroys a poem loudly.",
    "A dog builds an idea sadly.",
    "My friend looks at a poem silently.",
    "A scientist writes a book silently.",
    "The teacher destroys a book rarely.",
    "The singer builds an idea rarely.",
    "My friend admires a sandwich quickly.",
    "The singer looks at a sandwich loudly.",
    "An artist jumps over the computer sadly.",
    "The teacher admires the star boldly.",
    "The robot runs to the mountain quickly.",
    "An artist jumps over an idea silently.",
    "A dog runs to a poem silently.",
    "An artist jumps over the star rarely.",
    "The singer admires the wall gracefully.",
    "A scientist eats the mountain rarely.",
    "The cat builds the wall gracefully.",
    "My friend jumps over a poem sadly.",
    "A scientist admires a book quickly.",
    "A scientist looks at a poem loudly.",
    "A scientist builds the computer quickly.",
    "The cat looks at a poem happily.",
    "The teacher writes the wall silently.",
    "An artist eats the mountain gracefully.",
    "A dog destroys an idea happily.",
    "The robot jumps over the star quickly.",
    "The singer runs to the mountain quickly.",
    "An artist admires the computer sadly.",
    "The cat builds a sandwich boldly.",
    "An artist destroys a poem boldly.",
    "The robot eats a poem quickly.",
    "My friend jumps over an idea boldly.",
    "A dog looks at a book sadly.",
    "The teacher writes an idea boldly.",
    "The robot looks at a book quickly.",
    "A dog destroys the star quickly.",
    "The cat looks at the wall sadly.",
    "My friend runs to an idea boldly.",
    "The robot builds the mountain happily.",
    "An artist writes the mountain gracefully.",
    "A dog writes a poem sadly.",
    "My friend builds the star loudly.",
    "My friend eats a poem sadly.",
    "The singer destroys the computer gracefully.",
    "The robot eats the wall boldly.",
    "The teacher looks at a book silently.",
    "My friend writes a sandwich quickly.",
    "The robot jumps over a book boldly.",
    "The singer admires the wall silently.",
    "A dog jumps over an idea happily.",
    "My friend admires the wall sadly.",
    "A scientist eats a poem boldly.",
    "An artist writes an idea gracefully.",
    "An artist destroys the wall gracefully.",
    "The robot writes the mountain quickly.",
    "A scientist jumps over a book rarely.",
    "My friend writes an idea boldly.",
    "The cat jumps over a book rarely.",
    "A dog eats the star boldly.",
    "A dog runs to the computer gracefully.",
    "The cat runs to an idea boldly.",
    "The singer runs to the computer sadly.",
    "A dog destroys an idea silently.",
    "My friend writes a sandwich rarely.",
    "The teacher destroys a book boldly.",
    "The cat looks at the computer gracefully.",
    "The teacher builds the wall boldly.",
    "A dog admires the wall happily.",
    "The teacher admires a poem quickly.",
    "The cat builds the computer rarely.",
    "The singer admires the computer boldly.",
    "The teacher jumps over the star happily.",
    "The teacher runs to a book sadly.",
    "A dog builds a poem boldly.",
    "My friend eats a sandwich quickly.",
    "The robot eats a sandwich silently.",
    "The teacher destroys a sandwich sadly.",
    "A dog writes a poem loudly.",
    "An artist eats the wall boldly.",
    "The cat builds the computer quickly.",
    "A dog eats the star silently.",
    "The robot eats an idea happily.",
    "A dog writes the mountain loudly.",
    "A dog writes the computer happily.",
    "A dog writes the star rarely.",
    "My friend admires the wall loudly.",
    "The teacher jumps over a sandwich rarely.",
    "A scientist jumps over the mountain silently.",
    "The robot looks at the wall quickly.",
    "A scientist builds the mountain rarely.",
    "A scientist eats an idea happily.",
    "The singer jumps over the mountain loudly.",
    "A dog eats the star sadly.",
    "A scientist looks at a sandwich happily.",
    "The singer runs to the computer happily.",
    "The cat runs to a book silently.",
    "The cat destroys the computer loudly.",
    "The cat builds the computer sadly.",
    "My friend looks at the wall happily.",
    "The teacher builds a sandwich boldly.",
    "The singer eats the star quickly.",
    "The robot looks at an idea gracefully.",
    "A dog runs to the star happily.",
    "The teacher writes a sandwich happily.",
    "A scientist jumps over a sandwich boldly.",
    "An artist destroys the star gracefully.",
    "A scientist runs to a poem boldly.",
    "A dog looks at an idea loudly.",
    "The singer looks at a sandwich rarely.",
    "A dog admires a sandwich silently.",
    "The teacher eats a sandwich loudly.",
    "The cat admires a book quickly.",
    "A dog runs to the computer boldly.",
    "My friend admires an idea silently.",
    "The robot writes the wall loudly.",
    "My friend writes a book gracefully.",
    "A dog jumps over a sandwich sadly.",
    "A scientist looks at a book sadly.",
    "The robot writes a poem sadly.",
    "The singer admires the computer rarely.",
    "An artist jumps over a poem quickly.",
    "The teacher writes a sandwich rarely.",
    "The robot destroys an idea gracefully.",
    "An artist destroys an idea happily.",
    "My friend eats a poem rarely.",
    "The singer writes the star gracefully.",
    "The singer writes a poem silently.",
    "The singer destroys the star silently.",
    "The cat writes the mountain quickly.",
    "The cat eats the wall gracefully.",
    "The cat jumps over a sandwich silently.",
    "A dog runs to a poem boldly.",
    "The teacher jumps over the star rarely.",
    "The teacher eats a book silently.",
    "A dog admires a poem sadly.",
    "The singer admires the star happily.",
    "The cat looks at the star gracefully.",
    "A dog destroys the wall rarely.",
    "The teacher looks at a sandwich gracefully.",
    "A scientist writes a poem sadly.",
    "An artist runs to the wall silently.",
    "The singer jumps over the star gracefully.",
    "A dog writes the wall rarely.",
    "The robot admires an idea happily.",
    "The singer runs to the star quickly.",
    "My friend destroys the star quickly.",
    "The teacher runs to a poem quickly.",
    "My friend runs to a sandwich loudly.",
    "The cat writes the wall quickly.",
    "My friend runs to the computer quickly.",
    "A scientist admires a poem rarely.",
    "The cat destroys a sandwich silently.",
    "The robot destroys the mountain rarely.",
    "The cat admires the mountain loudly.",
    "The teacher admires an idea boldly.",
    "The teacher runs to a book silently.",
    "The singer jumps over a sandwich happily.",
    "The cat runs to the mountain quickly.",
    "The singer looks at an idea loudly.",
    "The teacher looks at a poem rarely.",
    "The cat destroys a poem gracefully.",
    "My friend looks at the mountain silently.",
    "The robot writes a poem happily.",
    "The robot destroys a poem happily.",
    "A scientist builds the wall loudly.",
    "My friend destroys the computer quickly.",
    "A scientist destroys the computer boldly.",
    "The robot jumps over a sandwich rarely.",
    "My friend admires a book sadly.",
    "The singer runs to an idea gracefully.",
    "The robot looks at a poem happily.",
    "A dog builds an idea rarely.",
    "The robot looks at the computer silently.",
    "The singer jumps over the computer rarely.",
    "The singer jumps over an idea rarely.",
    "A scientist looks at the star boldly.",
    "The singer jumps over an idea loudly.",
    "My friend builds an idea sadly.",
    "The teacher destroys a sandwich rarely.",
    "The robot writes the mountain loudly.",
    "My friend runs to an idea gracefully.",
    "A dog looks at the star sadly.",
    "The robot destroys a sandwich loudly.",
    "The cat destroys an idea loudly.",
    "A dog eats the mountain rarely.",
    "The singer writes the mountain sadly.",
    "The robot runs to the wall silently.",
    "A dog builds a book gracefully.",
    "The singer destroys the star sadly.",
    "The teacher destroys the mountain rarely.",
    "The robot looks at an idea boldly.",
    "The robot admires an idea quickly.",
    "A dog destroys the mountain loudly.",
    "A scientist admires an idea silently.",
    "A dog builds the star quickly.",
    "An artist runs to the wall boldly.",
    "My friend destroys a book quickly.",
    "A dog writes a sandwich sadly.",
    "The teacher writes the star sadly.",
    "The teacher runs to the mountain silently.",
    "The singer looks at an idea boldly.",
    "The teacher admires an idea rarely.",
    "My friend eats the computer silently.",
    "A scientist builds a sandwich silently.",
    "A scientist jumps over a book sadly.",
    "My friend runs to the mountain sadly.",
    "The robot destroys the mountain boldly.",
    "An artist builds the star silently.",
    "The teacher destroys a sandwich loudly.",
    "The teacher jumps over the mountain loudly.",
    "My friend writes a sandwich sadly.",
    "My friend destroys the computer loudly.",
    "The robot writes an idea happily.",
    "A scientist admires the mountain silently.",
    "The robot destroys a book quickly.",
    "A dog builds a sandwich gracefully.",
    "My friend builds the mountain loudly.",
    "An artist builds a sandwich loudly.",
    "My friend looks at a book boldly.",
    "The robot runs to an idea silently.",
    "The teacher builds a poem silently.",
    "The teacher builds a sandwich quickly.",
    "The singer jumps over the mountain happily.",
    "The cat looks at the wall boldly.",
    "My friend writes a sandwich boldly.",
    "The singer destroys an idea silently.",
    "A scientist destroys an idea gracefully.",
    "The robot looks at a poem sadly.",
    "An artist jumps over a book boldly.",
    "The singer admires the mountain rarely.",
    "The cat builds the wall rarely.",
    "An artist runs to the computer boldly.",
    "A scientist destroys the star sadly.",
    "The singer builds a sandwich sadly.",
    "An artist runs to the star gracefully.",
    "The robot jumps over the computer gracefully.",
    "The robot builds a poem boldly.",
    "My friend looks at the mountain happily.",
    "My friend runs to the star gracefully.",
    "The cat looks at a book sadly.",
    "My friend jumps over the wall boldly.",
    "The singer writes the star boldly.",
    "The robot looks at the computer boldly.",
    "A dog destroys the wall silently.",
    "An artist admires the wall boldly.",
    "The teacher destroys the computer sadly.",
    "My friend admires a sandwich happily.",
    "My friend admires a book quickly.",
    "A dog destroys the star gracefully.",
    "A dog jumps over the wall boldly.",
    "The teacher builds a sandwich sadly.",
    "A scientist eats a book sadly.",
    "The robot runs to the star sadly.",
    "The singer eats a poem rarely.",
    "The singer jumps over a poem sadly.",
    "A dog admires a poem loudly.",
    "A scientist destroys the mountain gracefully.",
    "The robot looks at the star quickly.",
    "An artist runs to an idea loudly.",
    "My friend jumps over the wall sadly.",
    "A scientist jumps over the mountain rarely.",
    "My friend looks at the computer quickly.",
    "An artist eats the computer gracefully.",
    "The teacher eats the computer silently.",
    "The teacher runs to an idea sadly.",
    "The robot builds an idea gracefully.",
    "A dog builds the star loudly.",
    "The teacher jumps over a sandwich happily.",
    "My friend builds the wall gracefully.",
    "The singer builds a poem gracefully.",
    "My friend admires the computer gracefully.",
    "A dog jumps over a poem rarely.",
    "A dog runs to a sandwich gracefully.",
    "The singer admires the mountain loudly.",
    "A dog admires the computer quickly.",
    "The singer builds the mountain boldly.",
    "A dog eats the computer happily.",
    "The cat jumps over the mountain rarely.",
    "The robot admires a book gracefully.",
    "A scientist jumps over the computer gracefully.",
    "The robot destroys the mountain sadly.",
    "The teacher eats the mountain loudly.",
    "The singer destroys the star gracefully.",
    "An artist eats a poem gracefully.",
    "A dog eats a poem happily.",
    "A dog looks at a sandwich gracefully.",
    "The robot eats a sandwich gracefully.",
    "My friend destroys the computer happily.",
    "The robot builds the computer quickly.",
    "A dog writes the star boldly.",
    "A scientist looks at the computer boldly.",
    "An artist jumps over the wall gracefully.",
    "A dog admires an idea rarely.",
    "My friend writes a poem boldly.",
    "The cat runs to a sandwich rarely.",
    "The teacher admires the mountain silently.",
    "The singer builds the wall silently.",
    "The robot looks at the wall sadly.",
    "The singer eats a sandwich happily.",
    "The cat eats the mountain happily.",
    "A dog writes an idea sadly.",
    "An artist builds a poem happily.",
    "The robot admires an idea loudly.",
    "My friend eats an idea boldly.",
    "The teacher runs to an idea loudly.",
    "The cat eats the mountain loudly.",
    "The singer runs to the star gracefully.",
    "The teacher eats a poem gracefully.",
    "A scientist builds a sandwich rarely.",
    "A dog jumps over a sandwich gracefully.",
    "An artist admires an idea rarely.",
    "A dog destroys the wall happily.",
    "The teacher looks at the mountain quickly.",
    "The robot destroys the computer happily.",
    "The cat writes the star silently.",
    "The robot writes the star silently.",
    "An artist looks at a poem sadly.",
    "The singer destroys a sandwich boldly.",
    "The teacher runs to the computer sadly.",
    "The cat runs to the star quickly.",
    "The teacher looks at the star boldly.",
    "An artist eats the computer quickly.",
    "The robot runs to the star happily.",
    "The robot destroys an idea quickly.",
    "An artist builds the mountain gracefully.",
    "The singer destroys the star boldly.",
    "The robot jumps over a sandwich sadly.",
    "A dog admires the computer loudly.",
    "The robot admires a poem boldly.",
    "My friend destroys the star silently.",
    "The teacher destroys the star gracefully.",
    "The singer eats a poem happily.",
    "The teacher writes the star silently.",
    "The teacher runs to the wall sadly.",
    "A scientist runs to the mountain quickly.",
    "The teacher eats the star gracefully.",
    "A scientist builds a sandwich sadly.",
    "An artist looks at the wall gracefully.",
    "An artist jumps over the star quickly.",
    "A dog writes the computer rarely.",
    "The teacher builds a book gracefully.",
    "An artist destroys a book happily.",
    "The teacher writes the computer silently.",
    "A scientist writes a sandwich happily.",
    "The teacher admires the computer boldly.",
    "The robot looks at a book happily.",
    "The cat admires the star boldly.",
    "The robot writes the wall boldly.",
    "The robot eats an idea rarely.",
    "The singer runs to a sandwich quickly.",
    "My friend jumps over a sandwich sadly.",
    "The singer looks at the computer sadly.",
    "The cat runs to an idea gracefully.",
    "A scientist writes the computer boldly.",
    "A dog builds a poem happily.",
    "The robot builds a poem loudly.",
    "The singer admires the mountain silently.",
    "The teacher eats the mountain sadly.",
    "My friend builds the star quickly.",
    "The robot jumps over an idea quickly.",
    "The cat eats the wall boldly.",
    "The teacher writes a book gracefully.",
    "An artist destroys the wall happily.",
    "The teacher jumps over the mountain happily.",
    "The teacher jumps over the star quickly.",
    "The teacher looks at an idea happily.",
    "A dog looks at a book rarely.",
    "The teacher looks at the wall sadly.",
    "The singer admires the wall quickly.",
    "My friend builds an idea gracefully.",
    "An artist runs to the star happily.",
    "An artist looks at the star rarely.",
    "The teacher runs to a sandwich rarely.",
    "My friend looks at a book quickly.",
    "A dog jumps over the mountain quickly.",
    "The robot writes the mountain happily.",
    "The singer jumps over the star quickly.",
    "The teacher jumps over the computer gracefully.",
    "The teacher runs to the star sadly.",
    "The robot jumps over a book loudly.",
    "The teacher admires the star loudly.",
    "The teacher writes the computer happily.",
    "The singer builds an idea silently.",
    "A dog destroys the computer boldly.",
    "The cat admires the wall gracefully.",
    "A scientist eats an idea sadly.",
    "The teacher looks at a book loudly.",
    "A dog runs to a sandwich loudly.",
    "A scientist admires the computer sadly.",
    "The singer destroys a sandwich sadly.",
    "A dog destroys the computer loudly.",
    "The robot writes the wall happily.",
    "The teacher builds the mountain sadly.",
    "The robot destroys the computer silently.",
    "The cat admires the computer rarely.",
    "The singer writes a poem quickly.",
    "The singer runs to the wall quickly.",
    "The teacher destroys the star boldly.",
    "An artist eats a sandwich happily.",
    "A scientist destroys the wall happily.",
    "The cat runs to a poem quickly.",
    "My friend admires a sandwich boldly.",
    "My friend looks at a book gracefully.",
    "The teacher jumps over a poem boldly.",
    "The singer builds a book loudly.",
    "The robot eats the star silently.",
    "A dog jumps over a poem boldly.",
    "The cat destroys the computer silently.",
    "My friend admires the computer happily.",
    "The teacher builds the wall silently.",
    "The singer admires the mountain quickly.",
    "The singer looks at the star happily.",
    "The robot looks at a sandwich boldly.",
    "My friend looks at an idea sadly.",
    "The teacher runs to a sandwich happily.",
    "The singer writes a book sadly.",
    "The robot jumps over the mountain quickly.",
    "A scientist admires a poem boldly.",
    "The singer destroys an idea sadly.",
    "The cat admires a book sadly.",
    "My friend runs to the wall loudly.",
    "An artist destroys a poem silently.",
    "The robot eats a poem silently.",
    "The cat eats the wall quickly.",
    "The robot writes an idea quickly.",
    "An artist builds a poem loudly.",
    "The singer builds the wall loudly.",
    "An artist looks at an idea loudly.",
    "An artist looks at the computer quickly.",
    "A scientist eats the wall rarely.",
    "The robot destroys the wall silently.",
    "The cat eats a book sadly.",
    "The teacher jumps over an idea boldly.",
    "The cat writes the mountain loudly.",
    "The teacher builds the computer loudly.",
    "A scientist admires a sandwich happily.",
    "The cat admires a poem rarely.",
    "A scientist jumps over a sandwich gracefully.",
    "The singer admires an idea loudly.",
    "A scientist runs to the wall boldly.",
    "An artist jumps over an idea gracefully.",
    "The singer eats an idea rarely.",
    "The singer writes the wall loudly.",
    "The robot writes a poem silently.",
    "My friend looks at a poem rarely.",
    "My friend looks at the wall boldly.",
    "The singer eats the wall loudly.",
    "My friend admires a sandwich silently.",
    "My friend builds the mountain quickly.",
    "An artist eats a sandwich quickly.",
    "A dog eats the computer boldly.",
    "A scientist writes an idea happily.",
    "An artist builds a book happily.",
    "The singer writes the wall sadly.",
    "The cat jumps over a poem rarely.",
    "The cat runs to an idea rarely.",
    "My friend writes a poem gracefully.",
    "The robot destroys the wall sadly.",
    "An artist builds an idea loudly.",
    "A scientist writes the star boldly.",
    "The cat looks at the computer quickly.",
    "An artist builds an idea quickly.",
    "A scientist runs to the wall quickly.",
    "The robot looks at the computer sadly.",
    "A dog jumps over the computer gracefully.",
    "A scientist admires the wall gracefully.",
    "A scientist jumps over the mountain sadly.",
    "My friend eats a book rarely.",
    "The teacher eats a poem rarely.",
    "My friend eats the star sadly.",
    "The teacher looks at a book gracefully.",
    "An artist builds a sandwich silently.",
    "The cat admires the mountain silently.",
    "The robot admires a sandwich gracefully.",
    "The singer writes a poem happily.",
    "My friend builds the mountain happily.",
    "The singer admires the star loudly.",
    "The singer jumps over a poem boldly.",
    "An artist destroys the mountain loudly.",
    "The robot destroys a book loudly.",
    "A dog jumps over a poem loudly.",
    "The cat admires a book rarely.",
    "The cat destroys a poem quickly.",
    "The cat builds the wall happily.",
    "An artist looks at the computer rarely.",
    "A dog eats the mountain boldly.",
    "The teacher writes a book happily.",
    "A scientist builds the wall silently.",
    "A scientist admires a poem sadly.",
    "An artist runs to a poem sadly.",
    "A scientist builds the mountain quickly.",
    "The teacher jumps over the computer boldly.",
    "My friend builds a poem sadly.",
    "A scientist writes a book happily.",
    "The teacher destroys the mountain happily.",
    "The teacher looks at an idea rarely.",
    "A dog writes a sandwich quickly.",
    "A dog destroys an idea gracefully.",
    "The singer destroys the mountain happily.",
    "The robot destroys a poem rarely.",
    "The teacher builds the computer boldly.",
    "The teacher eats a poem boldly.",
    "An artist writes a poem silently.",
    "The singer looks at the star gracefully.",
    "The cat builds the mountain loudly.",
    "An artist destroys a sandwich happily.",
    "The robot destroys the wall gracefully.",
    "A scientist destroys a sandwich loudly.",
    "The robot writes the computer quickly.",
    "An artist runs to an idea silently.",
    "The robot looks at the star sadly.",
    "An artist runs to the wall gracefully.",
    "The cat runs to a book boldly.",
    "The teacher jumps over an idea happily.",
    "The robot writes the computer rarely.",
    "A scientist builds a book silently.",
    "A dog admires a book rarely.",
    "The singer jumps over an idea gracefully.",
    "My friend admires an idea loudly.",
    "An artist writes a poem rarely.",
    "The teacher looks at an idea quickly.",
    "The cat eats the computer silently.",
    "The robot admires a book loudly.",
    "A dog writes a sandwich boldly.",
    "The teacher destroys a poem gracefully.",
    "A dog destroys the wall sadly.",
    "An artist jumps over a book sadly.",
    "The teacher writes a sandwich quickly.",
    "The singer runs to the star boldly.",
    "The robot looks at the mountain rarely.",
    "The singer eats the mountain quickly.",
    "A dog eats a poem silently.",
    "The teacher looks at the mountain rarely.",
    "The singer admires a poem quickly.",
    "A dog admires the star rarely.",
    "An artist writes the computer boldly.",
    "An artist eats an idea quickly.",
    "A scientist runs to the computer boldly.",
    "A scientist admires the mountain rarely.",
    "A scientist destroys an idea boldly.",
    "The cat jumps over an idea silently.",
    "The robot destroys the computer sadly.",
    "A scientist looks at the wall rarely.",
    "A scientist builds a poem quickly.",
    "The robot looks at a poem gracefully.",
    "The teacher builds a sandwich happily.",
    "The singer eats a book sadly.",
    "An artist looks at the wall boldly.",
    "The teacher admires a book quickly.",
    "The singer destroys a sandwich quickly.",
    "The singer writes the mountain quickly.",
    "The cat builds a book quickly.",
    "A scientist destroys the mountain quickly.",
    "A scientist builds an idea quickly.",
    "A scientist admires a sandwich rarely.",
    "A scientist jumps over the wall loudly.",
    "A dog destroys a poem loudly.",
    "My friend jumps over the mountain loudly.",
    "A scientist destroys a sandwich silently.",
    "The robot looks at an idea rarely.",
    "A scientist builds a poem silently.",
    "An artist writes the wall loudly.",
    "A dog builds a poem gracefully.",
    "An artist writes a book rarely.",
    "A scientist runs to an idea boldly.",
    "An artist destroys an idea gracefully.",
    "The cat writes a sandwich quickly.",
    "The singer looks at a poem quickly.",
    "My friend jumps over the mountain happily.",
    "A scientist builds a poem gracefully.",
    "The teacher jumps over the wall boldly.",
    "A dog eats the star quickly.",
    "My friend jumps over a sandwich happily.",
    "A scientist builds the star quickly.",
    "The singer writes a poem loudly.",
    "My friend writes a book silently.",
    "A scientist eats the star gracefully.",
    "My friend jumps over an idea loudly.",
    "The robot looks at the computer happily.",
    "The cat writes the mountain gracefully.",
    "The robot runs to the mountain happily.",
    "The cat admires an idea sadly.",
    "A dog eats a sandwich silently.",
    "The singer runs to the computer boldly.",
    "The singer admires a book silently.",
    "The robot destroys the computer rarely.",
    "My friend destroys a sandwich boldly.",
    "The robot runs to a book silently.",
    "A dog writes the mountain happily.",
    "An artist writes the mountain rarely.",
    "My friend builds a sandwich quickly.",
    "The cat admires the computer boldly.",
    "An artist writes a sandwich boldly.",
    "The robot destroys a poem sadly.",
    "An artist builds the star sadly.",
    "The teacher runs to the wall loudly.",
    "A dog destroys a poem gracefully.",
    "The singer destroys a book loudly.",
    "The singer builds an idea happily.",
    "The robot jumps over the mountain silently.",
    "The robot eats a book happily.",
    "The teacher writes a poem boldly.",
    "The teacher jumps over an idea rarely.",
    "A scientist writes a sandwich boldly.",
    "A dog runs to the star rarely.",
    "My friend destroys a book loudly.",
    "The robot builds a sandwich gracefully.",
    "An artist builds the computer boldly.",
    "An artist admires the computer rarely.",
    "A dog looks at an idea gracefully.",
    "The singer writes the star loudly.",
    "The singer builds the computer gracefully.",
    "My friend looks at a poem gracefully.",
    "A dog destroys the wall quickly.",
    "The cat builds a poem boldly.",
    "The teacher writes the wall loudly.",
    "An artist builds the mountain quickly.",
    "The robot builds a book boldly.",
    "The cat runs to a poem gracefully.",
    "The robot writes the star loudly.",
    "My friend jumps over a book loudly.",
    "A dog admires a sandwich gracefully.",
    "My friend jumps over an idea happily.",
    "A dog looks at the computer happily.",
    "My friend builds the star rarely.",
    "A dog writes the wall quickly.",
    "The singer destroys the wall gracefully.",
    "The teacher eats a book quickly.",
    "The teacher looks at an idea silently.",
    "An artist builds the mountain loudly.",
    "The teacher looks at the star silently.",
    "The cat looks at a sandwich loudly.",
    "The teacher admires the wall silently.",
    "The singer looks at an idea rarely.",
    "A scientist destroys a poem sadly.",
    "An artist builds the wall rarely.",
    "The singer runs to the mountain happily.",
    "My friend eats a poem happily.",
    "A dog eats a book loudly.",
    "The cat writes the star gracefully.",
    "The cat builds a book sadly.",
    "The singer destroys an idea loudly.",
    "The teacher jumps over the computer sadly.",
    "The singer writes a book silently.",
    "The robot jumps over the star boldly.",
    "The robot admires an idea silently.",
    "An artist eats the star silently.",
    "A scientist admires a poem quickly.",
    "The teacher looks at the star rarely.",
    "An artist runs to a poem boldly.",
    "My friend writes a poem silently.",
    "An artist eats a sandwich loudly.",
    "The robot writes a sandwich loudly.",
    "An artist destroys the computer happily.",
    "The cat looks at an idea loudly.",
    "The singer builds a poem boldly.",
    "The teacher eats the star silently.",
    "The singer looks at the computer silently.",
    "The robot eats a book rarely.",
    "The cat writes the star loudly.",
    "The robot jumps over the mountain boldly.",
    "The robot eats the computer gracefully.",
    "The singer admires the wall boldly.",
    "My friend runs to an idea quickly.",
    "The singer destroys a sandwich loudly.",
    "An artist jumps over a poem rarely.",
    "A dog destroys a poem quickly.",
    "A scientist writes a book rarely.",
    "My friend builds a book gracefully.",
    "The robot runs to the mountain silently.",
    "My friend runs to a book rarely.",
    "The singer jumps over the star sadly.",
    "My friend runs to the wall happily.",
    "The cat destroys the mountain gracefully.",
    "The robot builds the mountain boldly.",
    "The cat looks at the mountain loudly.",
    "A dog jumps over the computer happily.",
    "A dog eats the computer sadly.",
    "The robot admires the computer quickly.",
    "The cat looks at the computer loudly.",
    "My friend destroys a poem rarely.",
    "The robot jumps over the wall happily.",
    "An artist looks at the wall loudly.",
    "The cat runs to a poem sadly.",
    "A scientist builds the star loudly.",
    "The teacher runs to a book quickly.",
    "The robot jumps over a poem quickly.",
    "The cat writes a poem loudly.",
    "The singer builds the star boldly.",
    "My friend looks at a book silently.",
    "My friend runs to an idea sadly.",
    "A dog writes a poem silently.",
    "The teacher runs to the mountain happily.",
    "A dog writes the wall silently.",
    "The singer looks at the star sadly.",
    "The teacher jumps over a poem rarely.",
    "The singer writes the mountain silently.",
    "The singer runs to a poem happily.",
    "My friend writes the mountain quickly.",
    "My friend jumps over a poem happily.",
    "A dog destroys the star loudly.",
    "The singer writes the star silently.",
    "My friend destroys an idea happily.",
    "The cat builds an idea happily.",
    "A scientist eats an idea boldly.",
    "A scientist admires a book loudly.",
    "The robot looks at the mountain sadly.",
    "The cat builds the wall boldly.",
    "The singer runs to the star sadly.",
    "The singer writes a poem sadly.",
    "My friend runs to the computer loudly.",
    "An artist runs to an idea sadly.",
    "The teacher destroys an idea boldly.",
    "The cat writes an idea gracefully.",
    "The robot builds a poem sadly.",
    "The teacher runs to the star quickly.",
    "The singer builds the wall rarely.",
    "The teacher runs to a book happily.",
    "A scientist writes a book sadly.",
    "The cat writes the mountain rarely.",
    "The robot admires the mountain loudly.",
    "An artist builds the computer sadly.",
    "The teacher runs to a poem rarely.",
    "A scientist writes a sandwich loudly.",
    "My friend runs to the mountain silently.",
    "The teacher admires the star gracefully.",
    "A scientist builds the star happily.",
    "The teacher builds an idea happily.",
    "A dog destroys a book rarely.",
    "The robot jumps over a poem silently.",
    "The cat runs to an idea quickly.",
    "A scientist jumps over an idea boldly.",
    "A dog runs to the computer sadly.",
    "The robot writes a book quickly.",
    "A scientist admires the mountain happily.",
    "The robot eats an idea gracefully.",
    "The singer admires a sandwich loudly.",
    "My friend destroys a sandwich rarely.",
    "The robot builds a poem gracefully.",
    "A dog runs to a book sadly.",
    "A scientist jumps over a poem rarely.",
    "The teacher eats an idea boldly.",
    "The singer looks at the computer happily.",
    "A dog writes the wall gracefully.",
    "My friend eats the wall sadly.",
    "A scientist admires an idea rarely.",
    "The robot destroys a poem quickly.",
    "The teacher writes the star happily.",
    "The cat destroys a poem loudly.",
    "A scientist jumps over an idea happily.",
    "The cat looks at the mountain boldly.",
    "A dog runs to the mountain gracefully.",
    "A scientist jumps over an idea quickly.",
    "The cat writes a poem rarely.",
    "An artist eats a book sadly.",
    "My friend builds a poem rarely.",
    "A scientist jumps over the mountain boldly.",
    "The teacher runs to a poem happily.",
    "The robot runs to a book boldly.",
    "The singer jumps over the computer silently.",
    "The cat writes a book quickly.",
    "The cat admires the wall loudly.",
    "An artist jumps over the mountain silently.",
    "An artist builds a sandwich sadly.",
    "A dog eats a sandwich happily.",
    "My friend eats the mountain happily.",
    "A scientist jumps over the mountain happily.",
    "The singer destroys a poem loudly.",
    "An artist writes the wall gracefully.",
    "The teacher jumps over a sandwich loudly.",
    "A dog looks at a poem quickly.",
    "My friend destroys the computer rarely.",
    "A scientist admires the mountain quickly.",
    "An artist writes a book silently.",
    "My friend builds the computer boldly.",
    "My friend eats a sandwich rarely.",
    "The singer jumps over the wall gracefully.",
    "The singer runs to the mountain sadly.",
    "The singer admires the computer gracefully.",
    "A scientist looks at an idea sadly.",
    "The cat builds a book happily.",
    "The robot jumps over an idea loudly.",
    "An artist jumps over the computer gracefully.",
    "The singer admires the mountain sadly.",
    "The teacher destroys a poem sadly.",
    "The robot builds the computer rarely.",
    "My friend builds a sandwich sadly.",
    "A dog writes a poem boldly.",
    "The singer builds the mountain loudly.",
    "The singer runs to an idea sadly.",
    "The robot builds a sandwich rarely.",
    "The robot destroys a book gracefully.",
    "The teacher builds the computer happily.",
    "A scientist jumps over a book happily.",
    "The robot runs to a poem loudly.",
    "The teacher builds the wall gracefully.",
    "An artist destroys the mountain happily.",
    "The singer destroys the mountain rarely.",
    "The cat looks at the mountain happily.",
    "A dog admires a sandwich sadly.",
    "The singer runs to an idea happily.",
    "An artist runs to a sandwich gracefully.",
    "A dog destroys the star happily.",
    "The cat admires a poem loudly.",
    "The robot eats a sandwich happily.",
    "An artist eats a book quickly.",
    "A scientist builds an idea silently.",
    "A scientist jumps over a poem happily.",
    "A scientist runs to the computer happily.",
    "The robot admires the wall boldly.",
    "The singer destroys the computer quickly.",
    "A scientist destroys an idea sadly.",
    "The singer looks at the mountain boldly.",
    "A scientist admires the wall boldly.",
    "The singer runs to a poem gracefully.",
    "The singer builds the computer sadly.",
    "The cat writes the star sadly.",
    "The singer builds the wall quickly.",
    "The teacher writes the mountain sadly.",
    "The teacher eats a book loudly.",
    "The cat looks at a sandwich quickly.",
    "A dog runs to a poem loudly.",
    "An artist writes the computer quickly.",
    "A dog admires the wall loudly.",
    "The cat builds the mountain sadly.",
    "A dog admires a sandwich happily.",
    "A dog runs to the computer quickly.",
    "A scientist builds the wall gracefully.",
    "An artist eats the star sadly.",
    "An artist jumps over a poem happily.",
    "My friend destroys the wall happily.",
    "An artist writes the wall sadly.",
    "A scientist writes an idea boldly.",
    "A dog destroys a sandwich boldly.",
    "An artist eats the star rarely.",
    "A dog runs to an idea happily.",
    "A scientist destroys a poem loudly.",
    "An artist writes the star quickly.",
    "A dog looks at the wall sadly.",
    "A dog runs to an idea gracefully.",
    "The robot jumps over the star rarely.",
    "A scientist writes the star happily.",
    "The robot builds the star gracefully.",
    "An artist eats an idea rarely.",
    "The robot looks at a sandwich rarely.",
    "The cat looks at the mountain gracefully.",
    "The teacher destroys the star quickly.",
    "A scientist writes a poem boldly.",
    "A scientist runs to a sandwich boldly.",
    "My friend destroys the wall silently.",
    "The robot builds the star rarely.",
    "A dog builds a sandwich loudly.",
    "The robot admires the computer boldly.",
    "A dog writes the mountain quickly.",
    "A dog looks at a sandwich boldly.",
    "A dog destroys a book loudly.",
    "The robot eats the mountain sadly.",
    "The singer looks at a sandwich silently.",
    "The singer writes a sandwich sadly.",
    "The singer looks at the star quickly.",
    "An artist looks at the mountain sadly.",
    "The robot runs to the mountain sadly.",
    "The robot writes a book boldly.",
    "An artist writes the computer sadly.",
    "The singer jumps over an idea happily.",
    "The cat destroys the computer sadly.",
    "The cat writes the computer sadly.",
    "A dog jumps over the computer quickly.",
    "The cat jumps over a poem happily.",
    "A scientist jumps over a sandwich quickly.",
    "The robot runs to the star boldly.",
    "A scientist eats the star loudly.",
    "My friend destroys a book happily.",
    "The robot builds the mountain rarely.",
    "The cat eats the mountain quickly.",
    "The singer eats a book gracefully.",
    "The cat runs to a poem happily.",
    "A scientist writes a poem gracefully.",
    "A dog builds an idea silently.",
    "An artist destroys a sandwich loudly.",
    "The robot runs to the computer rarely.",
    "The cat admires an idea boldly.",
    "The teacher eats the computer rarely.",
    "The singer destroys the computer boldly.",
    "A dog writes a sandwich silently.",
    "My friend looks at the wall loudly.",
    "A dog admires the wall quickly.",
    "The teacher runs to a poem sadly.",
    "The cat writes the mountain sadly.",
    "The teacher looks at the star loudly.",
    "An artist jumps over the wall quickly.",
    "The cat runs to the wall sadly.",
    "A dog builds the star gracefully.",
    "The cat looks at a poem sadly.",
    "The singer destroys a book sadly.",
    "The teacher eats a book gracefully.",
    "A scientist runs to a sandwich gracefully.",
    "The singer writes the star sadly.",
    "The cat builds an idea silently.",
    "The cat builds a poem loudly.",
    "An artist eats the wall rarely.",
    "The cat runs to the mountain boldly.",
    "The cat builds a poem happily.",
    "The cat jumps over the mountain silently.",
    "An artist admires the computer loudly.",
    "The singer runs to a sandwich rarely.",
    "The teacher destroys an idea happily.",
    "The robot runs to a book quickly.",
    "The robot eats a poem rarely.",
    "My friend admires the computer quickly.",
    "The robot runs to an idea gracefully.",
    "The teacher eats a book sadly.",
    "My friend writes the mountain silently.",
    "The robot writes a book gracefully.",
    "The cat eats an idea loudly.",
    "The cat jumps over a book happily.",
    "The robot jumps over the wall rarely.",
    "The singer writes the star rarely.",
    "My friend writes the wall quickly.",
    "A scientist builds the mountain boldly.",
    "An artist destroys an idea loudly.",
    "The singer admires the wall loudly.",
    "The singer builds a poem silently.",
    "An artist looks at an idea silently.",
    "The cat eats the computer gracefully.",
    "The robot eats the mountain gracefully.",
    "The singer admires a poem loudly.",
    "An artist destroys the star silently.",
    "The singer runs to the star loudly.",
    "An artist eats the wall quickly.",
    "A scientist builds a sandwich gracefully.",
    "An artist runs to an idea quickly.",
    "A scientist admires an idea loudly.",
    "A scientist runs to the computer loudly.",
    "The robot eats a sandwich sadly.",
    "The robot writes the star rarely.",
    "The singer looks at the wall sadly.",
    "A scientist admires the wall sadly.",
    "My friend builds the wall happily.",
    "The teacher looks at an idea gracefully.",
    "My friend eats a book boldly.",
    "My friend jumps over the star happily.",
    "The cat builds the wall silently.",
    "The teacher admires a poem boldly.",
    "The cat jumps over an idea boldly.",
    "An artist builds a poem boldly.",
    "The robot builds the mountain gracefully.",
    "An artist writes the star sadly.",
    "The singer looks at a book quickly.",
    "The cat writes a book boldly.",
    "The teacher jumps over the computer happily.",
    "An artist runs to a sandwich happily.",
    "The singer writes a poem gracefully.",
    "The robot eats a poem loudly.",
    "The robot eats the computer happily.",
    "A scientist jumps over a book gracefully.",
    "A scientist eats the wall loudly.",
    "A dog looks at the star loudly.",
    "The robot admires a book boldly.",
    "A scientist jumps over a sandwich rarely.",
    "The cat looks at a book happily.",
    "A scientist jumps over the mountain gracefully.",
    "The singer builds a poem happily.",
    "A scientist builds the mountain sadly.",
    "A dog writes the mountain sadly.",
    "My friend jumps over a poem gracefully.",
    "The cat runs to the computer rarely.",
    "The cat builds a book gracefully.",
    "A dog jumps over a sandwich quickly.",
    "The robot runs to a poem gracefully.",
    "The singer runs to the wall silently.",
    "The robot destroys the mountain loudly.",
    "The cat destroys a poem happily.",
    "The robot runs to an idea quickly.",
    "The robot eats the computer silently.",
    "The teacher admires the wall gracefully.",
    "My friend jumps over a sandwich quickly.",
    "An artist looks at the wall quickly.",
    "The singer jumps over the mountain boldly.",
    "My friend looks at the computer gracefully.",
    "An artist destroys the wall silently.",
    "A dog jumps over the computer loudly.",
    "The robot looks at a sandwich silently.",
    "The teacher builds the star happily.",
    "The robot jumps over a poem loudly.",
]


vectorstore = FastembedVectorstore(FastembedEmbeddingModel.BGESmallENV15)
vectorstore.embed_documents(documents)

start_time = time.time()
vectorstore.search("Nature", 5)
print(f"Time taken: {time.time() - start_time} seconds")
