name: Publish wheels to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: PyO3/maturin-action/.github/workflows/maturin-release.yml@v1
    with:
      # Build release wheels for Windows, macOS (universal2), Linux (manylinux),
      # covering AMD64 and ARM where supported, plus an sdist.
      args: --release --sdist --skip-existing
    secrets:
      MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}


